name: TT语音打卡

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: TT

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【TT语音打卡】'
        run: |
          node ./Task/TT.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
