# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 易趣牛帮

on:
  workflow_dispatch:
  schedule:
     - cron: '7 0-12,23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:

        YQNB_yqnbHEADER: ${{ secrets.  YQNB_yqnbHEADER }}
        YQNB_yqnbBODY: ${{ secrets.  YQNB_yqnbBODY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/gz154838009/wgwy.git ~/wgwy
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/wgwy
          git checkout ZIYE
          npm install
      - name: '运行 【易趣牛帮】'
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/wgwy
          node Task/yqnb.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
